TeknikDestekElemanPaneli/Controllers/MesajController.cs
using DB.Models;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Newtonsoft.Json.Linq;
using TeknikDestekElemanPaneli.Models;

namespace TeknikDestekElemanPaneli.Controllers
{
    public class MesajController : Controller
    {
        private readonly ILogger<MesajController> _logger;
        private readonly Task3RealEcommerceContext _context;
        public MesajController(ILogger<MesajController> logger, Task3RealEcommerceContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult MesajIndex()
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            int admindenGelenMesajSayisi = _context.AdmindenTeknikDestegeMesajs.Where(p => p.OkunduBilgisi == false).Count();



            int kullanicidanGelenMesajSayisi = _context.KullanicidanTeknikDestegeMesajs.Where(p => p.OkunduBilgisi == false).Count();
            int firmadanGelenMesajSayisi = _context.FirmadanTeknikElemanaMesajs.Where(p => p.OkunduBilgisi == false).Count();
            int kargodanGelenMesajSayisi = _context.KargodanTeknikElemanaMesajs.Where(p => p.OkunduBilgisi == false).Count();
            int teknikElemandanGelenMesajSayisi = _context.TeknikElemanlarArasıMesajs.Where(p => (p.AlıcıEleman == id && p.OkunduBilgisi == false)).Count();

            KullaniciGelenMesajModel model = new KullaniciGelenMesajModel
            {
                _kullanicidanGelenMesajSayisi = kargodanGelenMesajSayisi,
                _admindenGelenMesajSayisi = admindenGelenMesajSayisi,
                _firmadanGelenMesajSayisi = firmadanGelenMesajSayisi,
                _kargodanGelenMesajSayisi = kargodanGelenMesajSayisi,
                _teknikElemandanGelenMesajSayisi = teknikElemandanGelenMesajSayisi
            };
            return View(model);
        }
        public ActionResult AdminGelenMesajlar()
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            var sonMesajlar = _context.AdmindenTeknikDestegeMesajs.GroupBy(p => p.MesajlasmaId).Select(p => p.OrderByDescending(p => p.MesajId).FirstOrDefault()).ToList();


            //var model = sonMesajlar.Select(p => new AdmindenGelenMesajModel
            //{
            //    _AdminAd = p.Admin.AdminAd,
            //    _AdminId = p.AdminId,
            //    _ElemanAd = p.Eleman.ElemanAd,
            //    _ElemanId = p.Eleman.TeknikElemanId,
            //    _Mesaj = p.Mesaj,
            //    _MesajBaslik = p.MesajBaslik,
            //    _MesajId = p.MesajId,
            //    _MesajlasmaId = p.MesajlasmaId,
            //    _OkunduBilgisi = p.OkunduBilgisi,
            //    _Tarih = p.Tarih
            //}).ToList();


            var model = sonMesajlar.Select(p => new AdmindenGelenMesajModel
            {
                _AdminAd = p.Admin != null ? p.Admin.AdminAd : "Admin",
                _AdminId = p.AdminId,
                _ElemanAd = p.Eleman != null ? p.Eleman.ElemanAd : "Sen",
                _ElemanId = id,
                _Mesaj = p.Mesaj,
                _MesajBaslik = p.MesajBaslik,
                _MesajId = p.MesajId,
                _MesajlasmaId = p.MesajlasmaId,
                _OkunduBilgisi = p.OkunduBilgisi,
                _Tarih = p.Tarih
            }).ToList();

            //var model = from p in sonMesajlar
            //            join l in _context.Admins on p.Admin.AdminId equals l.AdminId
            //            select new AdmindenGelenMesajModel
            //            {
            //                _AdminAd = p.Admin.AdminAd,
            //                _AdminId = p.Admin.AdminId,
            //                _ElemanAd = p.Eleman.ElemanAd,
            //                _ElemanId = p.Eleman.TeknikElemanId,
            //                _Mesaj = p.Mesaj,
            //                _MesajBaslik = p.MesajBaslik,
            //                _MesajId = p.MesajId,
            //                _MesajlasmaId = p.MesajlasmaId,
            //                _OkunduBilgisi = p.OkunduBilgisi,
            //                _Tarih = p.Tarih
            //            };
            //var gidenModel = model.ToList();
            return View(model);
        }
        public ActionResult AdmindenGelenMesajlasmaDetay(int mesajId)
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            int? mesajlasmaId = _context.AdmindenTeknikDestegeMesajs.Find(mesajId).MesajlasmaId;

            var admindenGelenler = from m in _context.AdmindenTeknikDestegeMesajs.Where(p => p.MesajlasmaId == mesajlasmaId)
                                   join l in _context.TeknikElemanlars.Where(p => p.TeknikElemanId == id) on m.ElemanId equals l.TeknikElemanId
                                   where m.MesajlasmaId == mesajlasmaId
                                   select new AdminTeknikMesajModel
                                   {
                                       _AliciAd = l.ElemanAd,
                                       _AliciId = l.TeknikElemanId,
                                       _GondericiAd = m.Admin.AdminAd,
                                       _Mesaj = m.Mesaj,
                                       _GondericiId = m.AdminId,
                                       _MesajBaslik = m.MesajBaslik,
                                       _MesajId = m.MesajId,
                                       _MesajlasmaId = m.MesajlasmaId,
                                       _OkunduBilgisi = m.OkunduBilgisi,
                                       _Tarih = m.Tarih,
                                       _Rol = false
                                   };

            var admineGonderilenler = from k in _context.TeknikdenAdmineMesajs.Where(p => p.MesajlasmaId == mesajlasmaId)
                                      join s in _context.TeknikElemanlars.Where(p => p.TeknikElemanId == id) on k.TeknikId equals s.TeknikElemanId
                                      where k.MesajlasmaId == mesajlasmaId
                                      select new AdminTeknikMesajModel
                                      {
                                          _AliciAd = k.Admin.AdminAd,
                                          _AliciId = k.AdminId,
                                          _GondericiAd = s.ElemanAd,
                                          _GondericiId = s.TeknikElemanId,
                                          _Mesaj = k.Mesaj,
                                          _MesajBaslik = k.MesajBaslik,
                                          _MesajId = k.MesajId,
                                          _MesajlasmaId = k.MesajlasmaId,
                                          _OkunduBilgisi = k.OkunduBilgisi,
                                          _Tarih = k.Tarih,
                                          _Rol = true
                                      };
            List<AdminTeknikMesajModel> model = new List<AdminTeknikMesajModel>();
            model.AddRange(admindenGelenler.Distinct().OrderByDescending(p => p._MesajId).ToList());
            model.AddRange(admineGonderilenler.Distinct().OrderByDescending(p => p._MesajId).ToList());
            model = model.OrderByDescending(p => p._Tarih).ToList();

            //var model = _context.AdmindenTeknikDestegeMesajs.Where(p => p.MesajlasmaId == mesajlasmaId).OrderByDescending(p => p.MesajId).Select(p => new AdmindenGelenMesajModel
            //{
            //    _AdminAd = p.Admin.AdminAd,
            //    _AdminId = p.Admin.AdminId,
            //    _ElemanAd = p.Eleman.ElemanAd,
            //    _Mesaj = p.Mesaj,
            //    _MesajBaslik = p.MesajBaslik,
            //    _ElemanId = p.Eleman.TeknikElemanId,
            //    _MesajId = p.MesajId,
            //    _MesajlasmaId = p.MesajlasmaId,
            //    _OkunduBilgisi = p.OkunduBilgisi,
            //    _Tarih = p.Tarih
            //}).ToList();
            var mesajim = _context.AdmindenTeknikDestegeMesajs.Find(mesajId);

            @ViewBag.ElemanId = mesajim.ElemanId;
            @ViewBag._mesajId = mesajId;
            @ViewBag._mesajlasmaId = mesajim.MesajlasmaId;
            return View(model);
        }
        public ActionResult AdmindenGelenMesajDetay(int mesajId)
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            var mesaj = _context.AdmindenTeknikDestegeMesajs.Where(p => p.MesajId == mesajId).OrderByDescending(p => p.MesajId).Select(p => new AdmindenGelenMesajModel
            {
                _AdminAd = p.Admin.AdminAd,
                _AdminId = p.Admin.AdminId,
                _ElemanAd = p.Eleman.ElemanAd,
                _ElemanId = p.Eleman.TeknikElemanId,
                _Mesaj = p.Mesaj,
                _MesajBaslik = p.MesajBaslik,
                _MesajId = p.MesajId,
                _MesajlasmaId = p.MesajlasmaId,
                _OkunduBilgisi = p.OkunduBilgisi,
                _Tarih = p.Tarih
            }).FirstOrDefault();

            return View(mesaj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TeknikdenAdmineCevap(TeknikdenAdmineMesaj _mesaj)
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {

TeknikDestekElemanPaneli/Controllers/SatisRedController.cs
using DB.Models;
using Microsoft.AspNetCore.Mvc;

namespace TeknikDestekElemanPaneli.Controllers
{
    public class SatisRedController : Controller
    {
        private readonly ILogger<SatisRedController> _logger;
        private readonly Task3RealEcommerceContext _context;
        public SatisRedController(ILogger<SatisRedController> logger, Task3RealEcommerceContext context)
        {
            _logger = logger;
            _context = context;
        }
        public ActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            var model = _context.SatisReds.OrderByDescending(p => p.RedId).Select(p => new SatisRed
            {
                Tarih = p.Tarih,
                FirmaId = p.FirmaId

            }).ToList();


            return View(model);
        }
    }
}

TeknikDestekElemanPaneli/Controllers/TeknikElemanController.cs
using DB.Models;
using Microsoft.AspNetCore.Mvc;
using System.Net.Mail;
using System.Net.Security;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using TeknikDestekElemanPaneli.Models;

namespace TeknikDestekElemanPaneli.Controllers
{
    public class TeknikElemanController : Controller
    {
        private readonly ILogger<TeknikElemanController> _logger;
        private readonly Task3RealEcommerceContext _context;
        public TeknikElemanController(ILogger<TeknikElemanController> logger, Task3RealEcommerceContext context)
        {
            _logger = logger;
            _context = context;
        }

        public int GirisKodDogrula(string teknikElemanMail)
        {
            Random rnd = new Random();
            int random = rnd.Next(100000, 999999 + 1);
            var admin = _context.Admins.Find(1);
            string basAdminMail = admin.Mail;
            string basAdminMailSifre = admin.MailSifre;
            var cred = new NetworkCredential(basAdminMail, basAdminMailSifre);
            var client = new SmtpClient("smtp.gmail.com", 587);
            var msg = new System.Net.Mail.MailMessage();
            msg.To.Add(teknikElemanMail);
            msg.Subject = "Giriş Kodu";
            msg.Body = $"Lütfen bu kodu girerek hesabınıza giriş yapınız <strong>{random}</strong>  eğer siz giriş yapmadıysanız hemen şifrenizi değiştirip başadminle mail yoluyla iletişime geçiniz";
            msg.IsBodyHtml = true;
            msg.From = new MailAddress(basAdminMail, "Doğrulama kodu", Encoding.UTF8);
            client.Credentials = cred;
            client.EnableSsl = true;
            ServicePointManager.ServerCertificateValidationCallback = delegate (object s, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors) { return true; };
            client.Send(msg);
            return random;
        }


        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string teknikElemanMail, string sifre)
        {
            if (_context.TeknikElemanlars.Any(p => p.Mail == teknikElemanMail))
            {
                var eleman = _context.TeknikElemanlars.FirstOrDefault(p => p.Mail == teknikElemanMail);
                if (eleman.Sifre == sifre)
                {
                    int kod = GirisKodDogrula(teknikElemanMail);
                    HttpContext.Session.SetInt32("teknikElemanId", eleman.TeknikElemanId);
                    HttpContext.Session.SetInt32("kod", kod);
                    return RedirectToAction("GirisKodDogrulama", "TeknikEleman");
                }
                else
                {
                    return RedirectToAction("Login", "TeknikEleman");
                }
            }
            else
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
        }
        [HttpGet]
        public ActionResult GirisKodDogrulama()
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            int? kod = HttpContext.Session.GetInt32("kod");
            if (!id.HasValue || !kod.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }


            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GirisKodDogrulama(int kod)
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            int? _kod = HttpContext.Session.GetInt32("kod");
            if (!id.HasValue || !_kod.HasValue)
            {
                return RedirectToAction("Login", "Admin");
            }
            if (kod == _kod)
            {
                _context.TeknikElemanGirislers.Add(new TeknikElemanGirisler
                {
                    ElemanId = id,
                    GirisBasariDurumu = true,
                    Tarih = DateTime.Now
                });
                _context.SaveChanges();
                return RedirectToAction("Index", "TeknikEleman");
            }
            else
            {
                return RedirectToAction("Login", "TeknikEleman");
            }

        }
        public ActionResult Index()
        {
            int? id = HttpContext.Session.GetInt32("teknikElemanId");
            if (!id.HasValue)
            {
                return RedirectToAction("Login", "TeknikEleman");
            }
            int iadeTalepSayisi = _context.IadeTaleps.Where(p => p.Aktiflik == true).Count();
            int yoldaIadeTalepSayisi = _context.YoldaIadeTalebis.Where(p => p.Onay == false).Count();
            int satisRedSayisi = _context.SatisReds.Count();
            int sikayetSayisi = _context.FirmadanKullaniciyaSikayets.Where(p => p.Aktiflik == true).Count() + _context.FirmadanKullaniciyaYorumCevapSikayets.Where(p => p.Aktiflik == true).Count() + _context.FirmadanYorumSikayets.Where(p => p.Aktiflik == true).Count() + _context.KullanicidanFirmayaSikayets.Where(p => p.Aktiflik == true).Count() + _context.KullanicidanFirmayaYorumCevapSikayets.Where(p => p.Aktiflik == true).Count() + _context.KullanicidanKargoFirmasiSikayetis.Where(p => p.Aktiflik == true).Count() + _context.KullanicidanYorumSikayets.Where(p => p.Aktiflik == true).Count() + _context.UrunSikayets.Where(p => p.Aktiflik == true).Count();
            int mesajSayisi = _context.AdmindenTeknikDestegeMesajs.Where(p => p.OkunduBilgisi == false).Count() + _context.KullanicidanTeknikDestegeMesajs.Where(p => p.OkunduBilgisi == false).Count() + _context.FirmadanTeknikElemanaMesajs.Where(p => p.OkunduBilgisi == false).Count() + _context.KargodanTeknikElemanaMesajs.Where(p => p.OkunduBilgisi == false).Count() + _context.TeknikElemanlarArasıMesajs.Where(p => (p.AlıcıEleman == id && p.OkunduBilgisi == false)).Count();

            //admibde teknik desteğe mesaj , kullanıcdan teknik desteğe mesaj , teknik elemanlar arası ,firmadan tekniğe, kargodan teknik elemana mesaj, 


            TeknikElemanIndexModel model = new TeknikElemanIndexModel()
            {
                _iadeTalepSayisi = iadeTalepSayisi,
                _yoldaIadeTalepSayisi = yoldaIadeTalepSayisi,
                _satisRedSayisi = satisRedSayisi,
                _sikayetSayisi = sikayetSayisi,
                _mesajSayisi = mesajSayisi
            };
            
            return View(model);
        }
        public ActionResult CikisYap()
        {

            HttpContext.Session.Clear();


            return RedirectToAction("Login", "TeknikEleman");
        }
    }
}

TeknikDestekElemanPaneli/Views/TeknikEleman/GirisKodDogrulama.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>KodDogrulama</title>
    <link href="~/css/koddogrulama.css" rel="stylesheet" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>
        body {
            background: url('../images/59278.jpg');
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-size: cover;
            background-position: center;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, Helvetica, sans-serif;
        }

        .container {
            width: 420px;
            background: transparent;
            color: #fff;
            border-radius: 10px;
            padding: 30px 40px;
            border: 2px solid rgba(255, 255, 255, .2);
            backdrop-filter: blur(20px);
            box-shadow: 0 0 10px rgba(0, 0, 0, .2);
        }

            .container h1 {
                font-size: 36px;
                text-align: center;
            }

            .container .input-box {
                width: 100%;
                height: 50px;
                position: relative;
                margin: 30px 0;
            }

        .input-box input {
            width: 100%;
            height: 100%;
            background: transparent;
            border: none;
            outline: none;
            border: 2px solid rgba(255, 255, 255, .2);
            border-radius: 40px;
            font-size: 16px;
            color: #fff;
            padding: 20px 45px 20px 20px;
        }

            .input-box input::placeholder {
                color: #fff;
            }

        .input-box i {
            position: absolute;
            right: 20px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 20px;
        }




        .container .btn {
            width: 100%;
            height: 45px;
            background: #fff;
            border: none;
            outline: none;
            border-radius: 40px;
            box-shadow: 0 0 10px rgba(0, 0, 0, .1);
            cursor: pointer;
            font-size: 16px;
            color: #333;
            font-weight: 600;
        }

        .container .change-password {
            font-size: 14.5px;
            text-align: center;
            margin: 20px 0 15px;
        }

        .change-password p a {
            color: #fff;
            text-decoration: none;
            font-weight: 600;
        }

            .change-password p a:hover {
                text-decoration: underline;
            }
    </style>
</head>
<body>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>

    <div class="container">
        <h1>Kod Doğrulama</h1>
        <form action="@Url.Action("GirisKodDogrulama","TeknikEleman")" method="post">
            @Html.AntiForgeryToken()
            <div class="input-box">
                <input type="password" name="kod" placeholder="Mailnize gelen kodu giriniz" required />
                <i class='bx bxs-lock-alt'></i>
            </div>
            <button type="submit" class="btn">Gönder</button>
        </form>
    </div>
</body>
</html>

TeknikDestekElemanPaneli/Views/TeknikEleman/Index.cshtml
@model TeknikElemanIndexModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>

    .anaDiv {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        padding: 20px;
        background-color: rgba(200, 255, 200, 1);
        min-height: 70vh;
    }

    .ayiriciDiv {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        align-items: center;
        margin: 10px;
    }

    .icDiv {
        border: solid 1px rgba(41, 26, 65, 0.1);
        border-radius: 8px;
        background-color: white;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin: 10px;
        padding: 20px;
        text-align: center;
        flex: 1;
        min-width: 200px;
        max-width: 300px;
        transition: transform 0.3s, box-shadow 0.3s;
    }

        .icDiv:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        }

        .icDiv h1 {
            color: green;
        }

        .icDiv p {
            color: #555;
        }

    a {
        text-decoration: none;
    }

</style>



<div class="anaDiv">
    <div class="ayiriciDiv">
        <div class="icDiv">
            <a href="@Url.Action("IadeTalepler","Iade")">
                <h1>İade Talepleri(@Model._iadeTalepSayisi)</h1>
                <p>Gelen iade talepleri burdan <br> görebilir ve süreci <br />yönetebilirsin </p>
            </a>
        </div>
        <div class="icDiv">
            <a href="@Url.Action("YoldaIadeTalepler","Iade")">
                <h1>Yolda İade Talepleri(@Model._yoldaIadeTalepSayisi)</h1>
                <p>Kargo yoldayken <br> istenen iadeler </p>
            </a>
        </div>

        <div class="icDiv">
            <a href="@Url.Action("MesajIndex","Mesaj")">
                <h1>Gelen Mesajlar(@Model._mesajSayisi)</h1>
                <p>Ve mesaj işlemlerini <br> burdan yönetebilirsin</p>
            </a>
        </div>
        
        <div class="icDiv">
            <a href="@Url.Action("Index","SatisRed")">
                <h1>Satış Reddleri(@Model._satisRedSayisi)</h1>
                <p>Şatış redleri <br> ve sebepleri görüntüle</p>
            </a>
        </div>
        <div class="icDiv">
            <a href="@Url.Action("Index","Urun")">
                <h1>Ürün Yönetimi</h1>
                <p>Ürünleri yönetmek  için tıkla</p>
            </a>
        </div>
        <div class="icDiv">
            <a href="@Url.Action("Index","Firma")">
                <h1>Firma Yönetimi</h1>
                <p>Firma işlemlerini burdan <br> yönetebilirsin</p>
            </a>
        </div>
    </div>
    <div class="ayiriciDiv">
        <div class="icDiv">
            <a href="@Url.Action("Index","KargoFirma")">
                <h1>Kargo Firma Yönetimi </h1>
                <p>Kargo firmalarını <br> yönetmek için tıklayınız</p>
            </a>
        </div>

        <div class="icDiv">
            <a href="@Url.Action("Index","SikcaSorulanlar")">
                <h1>Sıkça Sorulanlar</h1>
                <p>Kullancılara sunmak için sık sorunlar<br> kısmına ekleme yapabilirsin </p>
            </a>
        </div>
        <div class="icDiv">
            <a href="@Url.Action("Index","Kullanici")">
                <h1>Kullanıcı Yönetimi</h1>
                <p>Önerileri okumak için <br> tıklayınız</p>
            </a>
        </div>

    </div>
</div>

TeknikDestekElemanPaneli/Views/TeknikEleman/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <style>
        body {
            background: url('../images/59278.jpg');
            display: flex;
            justify-content: center;
            align-items: center;
            min-height: 100vh;
            background-size: cover;
            background-position: center;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: Arial, Helvetica, sans-serif;
        }

        .container {
            width: 420px;
            background: transparent;
            color: #fff;
            border-radius: 10px;
            padding: 30px 40px;
            border: 2px solid rgba(255, 255, 255, .2);
            backdrop-filter: blur(20px);
            box-shadow: 0 0 10px rgba(0, 0, 0, .2);
        }

            .container h1 {
                font-size: 36px;
                text-align: center;
            }

            .container .input-box {
                width: 100%;
                height: 50px;
                position: relative;
                margin: 30px 0;
            }

        .input-box input {
            width: 100%;
            height: 100%;
            background: transparent;
            border: none;
            outline: none;
            border: 2px solid rgba(255, 255, 255, .2);
            border-radius: 40px;
            font-size: 16px;
            color: #fff;
            padding: 20px 45px 20px 20px;
        }

            .input-box input::placeholder {
                color: #fff;
            }

        .input-box i {
            position: absolute;
            right: 20px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 20px;
        }




        .container .btn {
            width: 100%;
            height: 45px;
            background: #fff;
            border: none;
            outline: none;
            border-radius: 40px;
            box-shadow: 0 0 10px rgba(0, 0, 0, .1);
            cursor: pointer;
            font-size: 16px;
            color: #333;
            font-weight: 600;
        }

        .container .change-password {
            font-size: 14.5px;
            text-align: center;
            margin: 20px 0 15px;
        }

        .change-password p a {
            color: #fff;
            text-decoration: none;
            font-weight: 600;
        }

            .change-password p a:hover {
                text-decoration: underline;
            }
    </style>
</head>
<body>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <div class="container">
        <form action="@Url.Action("Login","TeknikEleman")" method="post">
            @Html.AntiForgeryToken()
            <h1>Teknik Eleman Giriş</h1>
            <div class="input-box">
                <input type="text" name="teknikElemanMail" required placeholder="Mailinizi giriniz" />
                <i class='bx bxs-lock-alt'></i>
            </div>
            <div class="input-box">
                <input type="password" name="sifre" required placeholder="Şifrenizi giriniz" />
                <i class='bx bxs-lock-alt'></i>
            </div>
            <button type="submit" class="btn">Gönder</button>
            <div class="change-password">


                <p>Şifrenizi unuttuysanız </p>

                <a href="@Url.Action("SifremiUnuttum","Admin")">Tıklayınız</a>



                <p style="color:red" id="mesaj"></p>
            </div>

        </form>
    </div>

</body>
</html>